// Generated by CoffeeScript 1.3.1

window.after = function(t, f) {
  return setTimeout(f, t);
};

window.every = function(t, f) {
  return setInterval(f, t);
};

$(document).ready(function() {
  var canvas, game;
  canvas = $('canvas#game');
  return window.game = game = new CarnageGame.Game(canvas);
});
