// Generated by CoffeeScript 1.3.1
var _base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

if ((_base = window.CarnageGame).Entities == null) {
  _base.Entities = {};
}

window.CarnageGame.Entities.Bullet = (function(_super) {

  __extends(_Class, _super);

  _Class.prototype.tileX = 0;

  _Class.prototype.tileY = 96;

  _Class.prototype.tileW = 8;

  _Class.prototype.tileH = 8;

  _Class.prototype.xr = 0;

  _Class.prototype.yr = 0;

  _Class.prototype.speed = 2;

  function _Class(owner, xa, ya) {
    this.owner = owner;
    this.xa = xa;
    this.ya = ya;
    this.xa *= 10;
    this.ya *= 10;
    this.xa += Math.random() * 3;
    this.ya += Math.random() * 3;
    this.x = this.owner.x + this.owner.tileW / 2;
    this.y = this.owner.y + this.owner.tileH / 2;
  }

  _Class.prototype.tick = function() {
    var hitEntities, hitEntity, _i, _len, _results;
    if (!this.move(this.xa, this.ya)) {
      this.remove();
    }
    hitEntities = this.level.getEntitiesWithin(this.x, this.y, this.x + this.tileW, this.y + this.tileH);
    _results = [];
    for (_i = 0, _len = hitEntities.length; _i < _len; _i++) {
      hitEntity = hitEntities[_i];
      if ((hitEntity instanceof CarnageGame.Entities.Mob) && !(hitEntity instanceof CarnageGame.Entities.Player)) {
        hitEntity.hurt(1);
        _results.push(this.remove());
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  _Class.prototype.move = function(xa, ya) {
    var stopped;
    stopped = false;
    if (!this.mayMove(xa, ya)) {
      stopped = true;
    }
    return !stopped;
  };

  _Class.prototype.render = function(screen) {
    return screen.render(this.x, this.y, this);
  };

  return _Class;

})(CarnageGame.Entity);
