// Generated by CoffeeScript 1.3.1
var _base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

if ((_base = window.CarnageGame).Entities == null) {
  _base.Entities = {};
}

window.CarnageGame.Entities.Bullet = (function(_super) {

  __extends(_Class, _super);

  _Class.prototype.tileX = 0;

  _Class.prototype.tileY = 96;

  _Class.prototype.tileW = 8;

  _Class.prototype.tileH = 8;

  _Class.prototype.xr = 0;

  _Class.prototype.yr = 0;

  _Class.prototype.speed = 10;

  function _Class(owner, xa, ya) {
    this.owner = owner;
    this.xa = xa;
    this.ya = ya;
    this.xa *= 10;
    this.ya *= 10;
    this.x = this.owner.x + this.owner.tileW / 2;
    this.y = this.owner.y + this.owner.tileH / 2;
  }

  _Class.prototype.tick = function() {
    if (!this.move(this.xa, this.ya)) {
      return this.remove();
    }
  };

  _Class.prototype.move = function(xa, ya) {
    var stopped;
    stopped = false;
    if (!this.mayMove(xa, ya)) {
      stopped = true;
    }
    return !stopped;
  };

  _Class.prototype.render = function(screen) {
    return screen.render(this.x, this.y, this);
  };

  return _Class;

})(CarnageGame.Entity);
