// Generated by CoffeeScript 1.3.1
var _base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

if ((_base = window.CarnageGame).Entities == null) {
  _base.Entities = {};
}

window.CarnageGame.Entities.Mob = (function(_super) {

  __extends(_Class, _super);

  function _Class(game) {
    this.game = game;
    this.direction = 0;
    this.health = 100;
  }

  _Class.prototype.hurt = function(dmg) {
    return this.health -= dmg;
  };

  return _Class;

})(CarnageGame.Entity);
