// Generated by CoffeeScript 1.3.1
var _base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

if ((_base = window.CarnageGame).Tiles == null) {
  _base.Tiles = {};
}

window.CarnageGame.Tiles.Floor = (function(_super) {

  __extends(_Class, _super);

  function _Class() {
    return _Class.__super__.constructor.apply(this, arguments);
  }

  _Class.prototype.name = "Floor";

  _Class.prototype.render = function(screen, level, x, y) {
    return _Class.__super__.render.call(this, screen, level, x, y);
  };

  return _Class;

})(CarnageGame.Tile);
