// Generated by CoffeeScript 1.3.1
var _base,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

if ((_base = window.CarnageGame).Tiles == null) {
  _base.Tiles = {};
}

window.CarnageGame.Tiles.Wall = (function(_super) {

  __extends(_Class, _super);

  function _Class() {
    _Class.__super__.constructor.call(this);
  }

  _Class.prototype.mayPass = function(level, x, y, entity) {
    return false;
  };

  return _Class;

})(CarnageGame.Tile);
