// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Entity = (function() {

  function _Class(level) {
    this.level = level;
    null;

  }

  _Class.prototype.tick = function() {
    return null;
  };

  _Class.prototype.render = function(context) {
    return null;
  };

  _Class.prototype.move = function(xa, ya) {
    return null;
  };

  return _Class;

})();
