// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Entity = (function() {

  _Class.prototype.tileX = 0;

  _Class.prototype.tileY = 0;

  _Class.prototype.tileW = 32;

  _Class.prototype.tileH = 32;

  _Class.prototype.xr = -2;

  _Class.prototype.yr = -2;

  _Class.prototype.speed = 1;

  function _Class(level) {
    this.level = level;
    this.removed = false;
  }

  _Class.prototype.init = function(level) {
    this.level = level;
    return null;
  };

  _Class.prototype.tick = function() {
    return null;
  };

  _Class.prototype.render = function(screen) {
    return null;
  };

  _Class.prototype.remove = function() {
    return this.removed = true;
  };

  _Class.prototype.move = function(xa, ya) {
    var stopped;
    xa *= this.speed;
    ya *= this.speed;
    stopped = true;
    if (xa !== 0 && this.mayMove(xa, 0)) {
      stopped = false;
    }
    if (ya !== 0 && this.mayMove(0, ya)) {
      stopped = false;
    }
    return !stopped;
  };

  _Class.prototype.mayMove = function(xa, ya) {
    var stopped, tile, x0, x1, xt, y0, y1, yt, _i, _j;
    stopped = false;
    x0 = ((this.x + xa) - this.xr) >> 5;
    x1 = ((this.x + xa) + this.xr + this.tileW) >> 5;
    y0 = ((this.y + ya) - this.yr) >> 5;
    y1 = ((this.y + ya) + this.yr + this.tileH) >> 5;
    for (yt = _i = y0; y0 <= y1 ? _i <= y1 : _i >= y1; yt = y0 <= y1 ? ++_i : --_i) {
      for (xt = _j = x0; x0 <= x1 ? _j <= x1 : _j >= x1; xt = x0 <= x1 ? ++_j : --_j) {
        tile = this.level.getTile(xt, yt);
        if (tile) {
          if (!tile.mayPass(this.level, xt, yt, this)) {
            stopped = true;
            return false;
          }
        }
      }
    }
    if (stopped) {
      return false;
    }
    this.x += xa;
    return this.y += ya;
  };

  _Class.prototype.intersects = function(x0, y0, x1, y1) {
    if (this.y + this.tileH < y0 || this.y > y1 || this.x + this.tileW < x0 || this.x > x1) {
      return false;
    }
    return true;
  };

  return _Class;

})();
