// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Game = (function() {

  function _Class(canvas) {
    var _this = this;
    this.canvas = canvas;
    this.level = new CarnageGame.Level('cg_intro.map');
    this.level.on('load', function(e) {
      if (e == null) {
        return console.log('level loaded');
      } else {
        return console.log(e);
      }
    });
  }

  return _Class;

})();
