// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Game = (function() {

  _Class.prototype.MAXFPS = 60;

  function _Class(canvas) {
    var _this = this;
    this.canvas = canvas;
    this.scrollX = 0;
    this.scrollY = 0;
    this.canvas[0].width = this.canvas.width();
    this.canvas[0].height = this.canvas.height();
    this.context = this.canvas[0].getContext('2d');
    this.screen = new CarnageGame.Screen(this.context);
    /*
          Mr.doob's stats lib
    */

    this.stats = new Stats();
    this.stats.setMode(0);
    this.stats.domElement.style.position = 'absolute';
    this.stats.domElement.style.top = '5px';
    this.stats.domElement.style.left = '5px';
    $('#canvas-wrapper').append(this.stats.domElement);
    /*
          Load level
    */

    this.level = new CarnageGame.Level('cg_intro.png');
    this.level.on('load', function(e) {
      if (e == null) {
        console.log('level loaded');
        _this.inputHandler = new CarnageGame.InputHandler;
        _this.player = new CarnageGame.Player(_this, _this.inputHandler);
        _this.player.findSpawn(_this.level);
        _this.level.add(_this.player);
        return _this.run();
      } else {
        return console.log(e);
      }
    });
  }

  _Class.prototype.run = function() {
    /*
          Run game loop
    */

    var _this = this;
    return every(1000 / this.MAXFPS, function() {
      _this.stats.begin();
      _this.tick();
      _this.render();
      return _this.stats.end();
    });
  };

  _Class.prototype.tick = function() {
    return this.level.tick();
  };

  _Class.prototype.render = function() {
    this.screen.clear();
    this.scrollX = this.player.x - this.canvas[0].width / 2;
    this.scrollY = this.player.y - this.canvas[0].height / 2;
    this.level.renderTiles(this.screen, this.scrollX, this.scrollY);
    return this.level.renderEntities(this.screen, this.scrollX, this.scrollY);
  };

  return _Class;

})();
