// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Key = (function() {

  function _Class() {
    this.pressed = false;
  }

  _Class.prototype.press = function() {
    return this.pressed = true;
  };

  _Class.prototype.release = function() {
    return this.pressed = false;
  };

  _Class.prototype.isPressed = function() {
    return this.pressed;
  };

  return _Class;

})();

window.CarnageGame.InputHandler = (function() {

  function _Class() {
    var down, left, right, up;
    up = new CarnageGame.Key();
    down = new CarnageGame.Key();
    right = new CarnageGame.Key();
    left = new CarnageGame.Key();
    this.keys = {
      up: up,
      down: down,
      right: right,
      left: left
    };
    $(document).keydown(function(e) {
      var keyCode;
      keyCode = e.keyCode;
      switch (keyCode) {
        case 38:
        case 87:
          return up.press();
        case 37:
        case 65:
          return left.press();
        case 40:
        case 83:
          return down.press();
        case 39:
        case 68:
          return right.press();
      }
    });
    $(document).keyup(function(e) {
      var keyCode;
      keyCode = e.keyCode;
      switch (keyCode) {
        case 38:
        case 87:
          return up.release();
        case 37:
        case 65:
          return left.release();
        case 40:
        case 83:
          return down.release();
        case 39:
        case 68:
          return right.release();
      }
    });
  }

  _Class.prototype.isPressed = function(id) {
    if (this.keys[id]) {
      return this.keys[id].isPressed();
    } else {
      return false;
    }
  };

  return _Class;

})();
