// Generated by CoffeeScript 1.3.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Player = (function(_super) {

  __extends(_Class, _super);

  _Class.prototype.tileX = 0;

  _Class.prototype.tileY = 64;

  function _Class(game, inputHandler) {
    this.game = game;
    this.inputHandler = inputHandler;
    this.direction = 0;
    this.health = 100;
  }

  _Class.prototype.findSpawn = function(level) {
    var spawn;
    spawn = level.getRandomSpawn();
    this.x = spawn.x * 32;
    return this.y = spawn.y * 32;
  };

  _Class.prototype.tick = function() {
    var xa, ya;
    xa = 0;
    ya = 0;
    if (this.inputHandler.isPressed('up')) {
      ya -= 2;
    }
    if (this.inputHandler.isPressed('left')) {
      xa -= 2;
    }
    if (this.inputHandler.isPressed('right')) {
      xa += 2;
    }
    if (this.inputHandler.isPressed('down')) {
      ya += 2;
    }
    this.x += xa;
    return this.y += ya;
  };

  _Class.prototype.render = function(screen) {
    return screen.render(this.x, this.y, this);
  };

  return _Class;

})(CarnageGame.Mob);
