// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Screen = (function() {

  _Class.prototype.tileSize = 32;

  function _Class(context) {
    this.context = context;
    this.spriteSheet = new Image();
    this.spriteSheet.src = "/images/sprites.png";
  }

  _Class.prototype.render = function(x, y, tile) {
    return this.context.drawImage(this.spriteSheet, tile.tileX * this.tileSize, tile.tileY * this.tileSize, tile.tileW * this.tileSize, tile.tileH * this.tileSize, x * this.tileSize, y * this.tileSize, tile.tileW * this.tileSize, tile.tileH * this.tileSize);
  };

  _Class.prototype.getWidth = function() {
    return this.context.canvas.width;
  };

  _Class.prototype.getHeight = function() {
    return this.context.canvas.height;
  };

  return _Class;

})();
