// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Screen = (function() {

  function _Class(context) {
    this.context = context;
    this.offsetX = 0;
    this.offsetY = 0;
    this.spriteSheet = new Image();
    this.spriteSheet.src = "/images/sprites.png";
  }

  _Class.prototype.render = function(x, y, tile) {
    return this.context.drawImage(this.spriteSheet, tile.tileX, tile.tileY, tile.tileW, tile.tileH, x - this.offsetX, y - this.offsetY, tile.tileW, tile.tileH);
  };

  _Class.prototype.renderWithRotation = function(x, y, rotation, tile) {
    this.context.save();
    this.context.translate(x + tile.tileW / 2 - this.offsetX, y + tile.tileH / 2 - this.offsetY);
    this.context.rotate(rotation);
    this.context.drawImage(this.spriteSheet, tile.tileX, tile.tileY, tile.tileW, tile.tileH, tile.tileW / 2 * -1, tile.tileH / 2 * -1, tile.tileW, tile.tileH);
    return this.context.restore();
  };

  _Class.prototype.setOffset = function(offsetX, offsetY) {
    this.offsetX = offsetX;
    this.offsetY = offsetY;
    return null;
  };

  _Class.prototype.getWidth = function() {
    return this.context.canvas.width;
  };

  _Class.prototype.getHeight = function() {
    return this.context.canvas.height;
  };

  _Class.prototype.clear = function() {
    return this.context.clearRect(0, 0, this.getWidth(), this.getHeight());
  };

  return _Class;

})();
