// Generated by CoffeeScript 1.3.1

if (window.CarnageGame == null) {
  window.CarnageGame = {};
}

window.CarnageGame.Tile = (function() {

  function _Class() {
    null;

  }

  _Class.prototype.tick = function() {
    return null;
  };

  _Class.prototype.render = function(context, level, x, y) {
    return null;
  };

  _Class.prototype.mayPass = function(level, x, y, entity) {
    return true;
  };

  _Class.prototype.hurt = function(level, x, y, source, dmg) {
    return null;
  };

  _Class.prototype.steppedOn = function(level, x, y, entity) {
    return null;
  };

  return _Class;

})();
